// <auto-generated />
using System;
using FloraManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FloraManagement.Persistence.Migrations
{
    [DbContext(typeof(FlowerDbContext))]
    partial class FlowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloraManagement.Domain.Entities.Flower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Multiplying")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Soil")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Flowers", (string)null);
                });

            modelBuilder.Entity("FloraManagement.Domain.Entities.Flower", b =>
                {
                    b.OwnsOne("FloraManagement.Domain.Entities.GrowingTips", "GrowingTips", b1 =>
                        {
                            b1.Property<Guid>("FlowerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPhotophilous")
                                .HasColumnType("boolean")
                                .HasColumnName("IsPhotophilous");

                            b1.Property<int>("TemperatureCelsius")
                                .HasColumnType("integer")
                                .HasColumnName("TemperatureCelsius");

                            b1.Property<int>("WateringPerWeek")
                                .HasColumnType("integer")
                                .HasColumnName("WateringPerWeek");

                            b1.HasKey("FlowerId");

                            b1.ToTable("Flowers");

                            b1.WithOwner()
                                .HasForeignKey("FlowerId");
                        });

                    b.OwnsOne("FloraManagement.Domain.Entities.VisualParameters", "VisualParameters", b1 =>
                        {
                            b1.Property<Guid>("FlowerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AverageSize")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AverageSize");

                            b1.Property<string>("LeafColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LeafColor");

                            b1.Property<string>("StemColor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("StemColor");

                            b1.HasKey("FlowerId");

                            b1.ToTable("Flowers");

                            b1.WithOwner()
                                .HasForeignKey("FlowerId");
                        });

                    b.Navigation("GrowingTips")
                        .IsRequired();

                    b.Navigation("VisualParameters")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
